- name: "Hadoop Cluster Configuration"
  hosts: MasterNode
  vars:
          - jdk_package: "jdk-8u171-linux-x64.rpm"
          - hadoop_package: "hadoop-1.2.1-1.x86_64.rpm" 
  vars_prompt:
          - name: "mn_dir"
            prompt: "Enter the directory name for MasterNode"
            private: no
          - name: "mn_ip"
            prompt: "Enter Ip Address For MasterNode"
            private: no
          - name: "mn_port_no"
            prompt: "Enter The Port Number For MasterNode"
            private: no          
  tasks:
          - name: "Copy JDK Pacakge"
            copy:
                    src: "/Task11.1/{{ jdk_package }}"
                    dest: "/home/ec2-user/"

          - name: "Copy Hadoop Package"
            copy:
                    src: "/Task11.1/{{ hadoop_package }}"
                    dest: "/home/ec2-user/"
          
          - name: "Install JDK"
            command: "rpm -ivh {{ jdk_package }}"
            register: jdk

          - debug:
                   var: jdk

          - name: "Install Hadoop"
            command: "rpm -ivh {{ hadoop_package }} --force"
            register: hadoop

          - debug:
                  var: hadoop

          - name: "Create Directory For Master Node"
            file:
                     path: "/{{ mn_dir }}"
                     state: directory

          - name: "Configure hdfs-site.xml file"
            template:
                    src: "/Task11.1/hdfs-site.xml.j2"
                    dest: "/etc/hadoop/hdfs-site.xml"

          - name: "Configure core-site.xml file"
            template:
                     src: "/Task11.1/core-site.xml.j2"
                     dest: "/etc/hadoop/core-site.xml"

          - name: "Format Master Node"
            shell: "echo Y | hadoop namenode -format"
            register: format

          - debug: 
                var: format.stdout

          - name: "Stating Hadoop Daemon Service"
            shell: "sudo hadoop-daemon.sh start namenode"
       
          - name: "Check whether namenode start or not"
            command: "jps"
            register: nn_jps 

          - debug:
                   var: nn_jps

       
